import Button from "@mui/material/Button";
import './globals.css'
import Link from 'next/link'
import * as React from 'react';

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }){
  return (
    <html lang="en">
      <body className={inter.className}>
      {children}
        <ul className='flex'>
          <li className='mr-2'>
            <Link href="/dashboard">Home</Link>
          </li>
          <li className='mr-2'>
            <Link href="about">About</Link>
          </li>
          </ul>
          ini dari layout
        <Button variant="contained">Pet Shop</Button>
        </body>
    </html>
  );
}
  
